Feature: equality helper function
ryangjchandler/puny pull request #17
Opened 2021-01-23 14:11 UTC by thinkverse

This PR adds a rudimentary `eq` function for checking equality. It was talked about in the "minimal testing" blog post that inspired Puny, but it wasn't in the framework. So I decided to create a simple `eq` function.

Had to add a phpdoc for the `eq()` since `mixed` type-hinting isn't supported in 7.4 sadly.

2021-01-23 14:51 UTC, ryangjchandler commented
@thinkverse Instead of wrapping the callables in Closures, couldn't we just invoke them using `call_user_func` or just `$first()`?

2021-01-23 14:56 UTC, thinkverse commented
Took inspiration from what you did in the `Spy` class, but `call_user_func` and just calling it would to the same really, guess it would simply be a preference, not sure which would be the most performant though. 🤔
https://github.com/ryangjchandler/puny/blob/f9c461675bbb9f3ac6c9c574a9fa154ffd1f3e90/src/Support/Spy.php#L17

2021-01-23 15:22 UTC, ryangjchandler requested changes

2021-01-23 15:25 UTC, ryangjchandler commented
> Took inspiration from what you did in the `Spy` class, but `call_user_func` and just calling it would to the same really, guess it would simply be a preference, not sure which would be the most performant though. 🤔
> https://github.com/ryangjchandler/puny/blob/f9c461675bbb9f3ac6c9c574a9fa154ffd1f3e90/src/Support/Spy.php#L17

Yeah, performance is a good point. The only reason I used `Closure` is because you can't store `callable` types as a property because it's a weird union type (I think).

2021-01-23 15:27 UTC, thinkverse commented on src/helpers.php
> +    return $expected == $actual;
That would also make the first strict comparison kind-of redundant so that could be removed then? So, remove the first `if`, change the comparison to strict and change `::fromCallable` to `call_user_func` or `$variable()`.

2021-01-23 15:31 UTC, thinkverse commented
> can't store `callable` types as a property because it's a weird union type (I think).

Yeah, PHP's type-hinting is pretty limited when it comes to the non-scalar types, though it's a bit better now in the latest major release.

2021-01-23 15:34 UTC, ryangjchandler commented on src/helpers.php
> +    return $expected == $actual;
Yeah I think that should do it.

2021-01-23 15:38 UTC, thinkverse commented on src/helpers.php
> +    return $expected == $actual;
What do you think about this? 🤔
```
$expected = is_callable($expected) ? $expected() : $expected;
$actual = is_callable($actual) ? $actual() : $actual;

return $expected === $actual;
```

2021-01-23 15:45 UTC, ryangjchandler commented on src/helpers.php
> +    return $expected == $actual;
Yeah, that works for me. I think at some point in the future I'd like to add in some sort of "call handler" so you could for example, run all callbacks through Laravel's container or something.

2021-01-23 15:49 UTC, thinkverse commented on src/helpers.php
> +    return $expected == $actual;
That would be cool. I pushed the changes to the `eq` function, so I'll resolve this convo. 🙂

2021-01-23 15:51 UTC, ryangjchandler approved these changes

2021-01-23 15:54 UTC, ryangjchandler commented
@thinkverse Would you be up for documenting these changes in the README? No worries if not, I can do it before tagging :)

2021-01-23 15:57 UTC, thinkverse commented
Sure, I'll add a small section in the README for it. 🙂

2021-01-23 16:08 UTC, thinkverse commented
Writing documentation isn't really a strong suit but there ya' go. 👍

2021-01-23 16:09 UTC, ryangjchandler commented on README.md
> +### Comparing equality with eq
```suggestion
### Checking equality with eq
```

2021-01-23 16:11 UTC, ryangjchandler requested changes

2021-01-23 16:11 UTC, ryangjchandler commented on README.md
> +### Comparing equality with eq
```suggestion
### Checking equality with eq
```

2021-01-23 16:11 UTC, ryangjchandler commented on README.md
> +You can use the `eq` function to strictly compare if two values are equal. The first argument is your expected value. The second is your actual value. But they are interchangable and just a suggestio
```suggestion
You can use the `eq` function to check if two values are **strictly** equal. The first argument is your expected value. The second is your actual value. But they are interchangable and just a suggestion. The return value is a `bool` result of the comparison check.
```

2021-01-23 16:12 UTC, ryangjchandler commented
I'm also wondering now whether the `return` value of `eq` should be wrapped in an `ok`...

2021-01-23 16:14 UTC, thinkverse commented on README.md
> +### Comparing equality with eq
Adding that locally since I need to update the link as well. 👍

2021-01-23 16:18 UTC, thinkverse commented
> I'm also wondering now whether the `return` value of `eq` should be wrapped in an `ok`...

Wouldn't that make the function do two things instead of just one though, it would do both the comparison and run the check instead of just comparing.

2021-01-23 16:18 UTC, ryangjchandler commented
> > I'm also wondering now whether the `return` value of `eq` should be wrapped in an `ok`...
> 
> Wouldn't that make the function do two things instead of just one though, it would do both the comparison and run the check instead of just comparing.

Yeah, that's true. But it would be more of an equal assertion.

2021-01-23 16:24 UTC, thinkverse commented
Let's see so `eq(sum(1 + 2), 3, 'can sum two integers');` instead of `ok(eq(sum(1 + 2), 3), 'can sum two integers');`

Does seem cleaner with the wrap actally.

2021-01-23 17:22 UTC, ryangjchandler commented
Yeah, let's add the ok() into eq(). Otherwise the eq() is kind of redundant because you could just do the === yourself.

2021-01-23 17:24 UTC, thinkverse commented
Ok, I'll push that change up tomorrow if you don't do it later today, for now, I'm too tired and hungry to do any work. 👍

2021-01-23 17:25 UTC, ryangjchandler commented
No worries man. Appreciate the help!

2021-01-25 11:51 UTC, ryangjchandler approved these changes

2021-01-25 11:51 UTC, merged

2021-01-25 11:52 UTC, ryangjchandler commented
Thanks for the work on this @thinkverse, really appreciate it!